### ISSUE TITLE
Confirm compatibility with GNU GPL v2 license

### ISSUE THREAD

**Issue by SP-NTX** [franck-vmd/Boeing-777-Flightgear#1]
1. As the title says.
2. Deleting the issue - without even explaining why or anything, nor telling if it is actually compatible with GNU GPL license won't help.
3. Confirm that the model is compatible with GNU GPL v2 license, that's the main problem

**Comment by franck-vmd** [comment]
Hello 

Want help with GPL? 

I have this to help you: https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.fr.html

Have a nice weekend

**Comment by SP-NTX** [comment]
Thanks Franck.
Can you just confirm that model and everything is yours? Just for clarification.
Really happy to see good 777 there.
Kind Regards
SP-NTX

**Comment by franck-vmd** [comment]
Hello, yes I confirm, have a good day

**Comment by SP-NTX** [comment]
Thank you, I am going to close the issue. Have a good day, and wishing you all the best with your project.
Kind Regards
SP-NTX
