### ISSUE TITLE
Bug system autopilot LNAV

### ISSUE THREAD

**Issue by brooks95** [franck-vmd/Boeing-777-Flightgear#15]
Bonjour j’aimerais signaler un bug système.
Lorsque j’effectue des vols long qui ont 
plusieurs points au bout d’un certain nombre de points l’avions fait demi tour et repart en arrière. 

Hello, I would like to report a system bug.
When I make long flights which have
several points after a certain number of points the plane turns around and goes back.

**Comment by franck-vmd** [comment]
Bonjour, merci pour le signalement. Peux-tu me dire le trajet (vol long) que je dois suivre pour voir ce qui se passe?

**Comment by brooks95** [comment]
Un vol entre Paris et Los Angeles ou un vol entre Paris et dubai. Et vous allez remarquer que au bout d’un certain nombre de point l’avion va faire demi tour.

**Comment by franck-vmd** [comment]
ok merci , combien de points ?

**Comment by brooks95** [comment]
Je sais pas exactement mais je dirais au bout de 10 ou  15 points il fait demi tour

**Comment by franck-vmd** [comment]
ok mes sur combien de point ? et si tu peut me donner les fréquence radio  ils de Los Angeles s'il te plait car j'arrive pas a les avoir correctement KLAX , merci

**Comment by brooks95** [comment]
Voici toute les fréquences ils de KLAX:
![IMG_6894](https://github.com/franck-vmd/Boeing-777-Flightgear/assets/162732123/263abb41-e508-4344-812a-f469d45a5c2a)

Ensuite dans mes plans de vol il y a souvent 30 points en général.

**Comment by franck-vmd** [comment]
super merci

**Comment by franck-vmd** [comment]
Bonjour aucun Bug systeme autopilot LNAV

pour le CDU voir sur le EFB ----> Document -----> CDU pour explication d'utilisation ou sur ma chaine youtube 

https://youtu.be/jpuPxSbWVmI?si=7jkm8IunuTsgCa0-

Ma feuille de navigation LFQQ piste 26 a OMDB piste 12L

![Image](https://i.ibb.co/TPTb4wm/LFQQ-26-OMDB-12-L.jpg)

image prise sur le parcourt 

![Image](https://i.ibb.co/s9CPcTz/01.jpg)

![Image](https://i.ibb.co/w6DTPw4/02.jpg)

![Image](https://i.ibb.co/S04jnn1/03.jpg)

![Image](https://i.ibb.co/qMtLv8n/04.jpg)

![Image](https://i.ibb.co/0MpZj77/05.jpg)

![Image](https://i.ibb.co/gwHNv8K/06.jpg)

![Image](https://i.ibb.co/N9VWPGW/07.jpg)

![Image](https://i.ibb.co/Vvsf8T7/08.jpg)

![Image](https://i.ibb.co/J3RHyhF/09.jpg)

![Image](https://i.ibb.co/ThCcBLQ/10.jpg)

![Image](https://i.ibb.co/376FzPT/11.jpg)

![Image](https://i.ibb.co/WxQyccY/12.jpg)

![Image](https://i.ibb.co/48RkJm2/13.jpg)

![Image](https://i.ibb.co/gJ8tWWt/14.jpg)
