### ISSUE TITLE
Navigation Display Bug

### ISSUE THREAD

**Issue by snikskytter** [franck-vmd/Boeing-777-Flightgear#19]
When first officer's side ND display mode is changed in Captain's View, ND display mode on captain's side changes, same issue happens with the range selector. When the view mode is changed to First Officer's View, the issue remains.

**Comment by franck-vmd** [comment]
I made the necessary changes.

**Comment by franck-vmd** [comment]
Everything should be up and running now.

**Comment by snikskytter** [comment]
Thank you! I will test and close the issue

**Comment by snikskytter** [comment]
Thank you! I will test it tomorrow, close the issue if it's fixed and let you know.

**Comment by snikskytter** [comment]
Both Navigation Displays are now functioning properly. The issue is solved. Thank you for the quick fix and congratulations on one of the best FG mods ever :) 

I will now close the report.

**Comment by franck-vmd** [comment]
cool thank you
