### ISSUE TITLE
VOR L/R buttons can not be pushed back down

### ISSUE THREAD

**Issue by snikskytter** [franck-vmd/Boeing-777-Flightgear#22]
VOR L/R buttons on both side can not be pushed back down to OFF or ADF position

![fgfs-20240525200445](https://github.com/franck-vmd/Boeing-777-Flightgear/assets/168301658/8e01acef-367c-405a-a40d-0c615bdeb838)

**Comment by franck-vmd** [comment]
Hello, thank you for the report
