### ISSUE TITLE
Aircraft don't appear

### ISSUE THREAD

**Issue by Lucasmachado38** [franck-vmd/Boeing-777-Flightgear#24]
I went to open the aircraft in the simulator, but it isn't showing up. What went wrong? I installed the new 777-VMD.

![Sem título](https://github.com/franck-vmd/Boeing-777-Flightgear/assets/171390391/7de72d5e-0405-4a8b-a719-6d5329a6a7f3)

**Comment by franck-vmd** [comment]
Good evening, what? x8 , x9, 200F? or all? 
and how did you install it?

**Comment by franck-vmd** [comment]
forget a set . XML
it must be good now
