### ISSUE TITLE
Demande de fonctionnalité 

### ISSUE THREAD

**Issue by erwan-gg** [franck-vmd/Boeing-777-Flightgear#27]
> Serait-il possible d'avoir des antenne wifi de ce genre sur les différents 777 notamment le 200er et le 300er
> 
> ![WhatsApp Image 2024-07-13 à 08 34 06_7f5baa1d](https://private-user-images.githubusercontent.com/162732123/348457357-a1024250-7b4e-4a1b-a015-4f597fa79a97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzYwNjYsIm5iZiI6MTcyMDkzNTc2NiwicGF0aCI6Ii8xNjI3MzIxMjMvMzQ4NDU3MzU3LWExMDI0MjUwLTdiNGUtNGExYi1hMDE1LTRmNTk3ZmE3OWE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwNTQyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDM4MTBmODEzZTU2Y2E3YjQ4OGIwMmZjZTZlOWNiNGE3ZWYxZjAwNjQ0YWI3N2YyZDkxNTkzOGNhNWFkZTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pBdLJGoXkdtya_dNtwcQOP23VfWQnQCc22763awYG2g)
> 
> Ensuite j'ai remarqué que sur votre 777-200er il y'a pas la lumière en bout d'aille alors que sur l'appareil réel il y'a cette lumière en bout d'aile. Serait-il possible de rajouter la lumière.(Come sur le 300er)
> 
> ![WhatsApp Image 2024-07-13 à 08 46 50_7cac48c0](https://private-user-images.githubusercontent.com/162732123/348457761-043d714d-3c06-408b-b952-5efcd9f499dd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzYwNjYsIm5iZiI6MTcyMDkzNTc2NiwicGF0aCI6Ii8xNjI3MzIxMjMvMzQ4NDU3NzYxLTA0M2Q3MTRkLTNjMDYtNDA4Yi1iOTUyLTVlZmNkOWY0OTlkZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwNTQyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Yjk0MTMzMWFiMDdlNDBkZDNmNTU2YTVlZTAwNzVhZmI3ZTgyYWIwYmRiMjQzOWE2NjVkNjIzZTdiODkyNjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8hnupq1R7nqTAnHpNA_I3F4eH2QDV1ODt5XN3akp_ws) ![WhatsApp Image 2024-07-13 à 08 46 50_7699b102](https://private-user-images.githubusercontent.com/162732123/348457764-a36e7e94-4b9c-45a6-b257-32b6a4e275e0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzYwNjYsIm5iZiI6MTcyMDkzNTc2NiwicGF0aCI6Ii8xNjI3MzIxMjMvMzQ4NDU3NzY0LWEzNmU3ZTk0LTRiOWMtNDVhNi1iMjU3LTMyYjZhNGUyNzVlMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwNTQyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjA4MDk4MzgyZjI4MWViODRjYTQ2ZWI1ZDM1NGM4MzgyNjRkOGZmMTQwMjUzN2E5M2I4OGIwNTM2YWU3YzU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sfMZRjoC8Z3z5wNlog6tv25-p27VWCeXbRaIMXd5-1w)

**Comment by franck-vmd** [comment]
Bonjour je ne vois pas les images

**Comment by erwan-gg** [comment]
POUR LES ANTENNES WIFI

![WhatsApp Image 2024-07-13 à 08 34 06_7f5baa1d](https://github.com/user-attachments/assets/ed5ce150-ca9d-4065-8c32-d9e59a0098b6)

POUR LES LUMIERE EN BOUT D'AILE SUR LE 200ER

![WhatsApp Image 2024-07-13 à 08 46 50_7cac48c0](https://github.com/user-attachments/assets/f58473f7-8222-4283-8c4c-442919360df6)


![WhatsApp Image 2024-07-13 à 08 46 50_7699b102](https://github.com/user-attachments/assets/b1a6b4d9-eb0f-4fe2-890f-2176166bc2e4)

**Comment by franck-vmd** [comment]
Oui ça sera fait , merci
