### ISSUE TITLE
Bug plan de vol

### ISSUE THREAD

**Issue by erwan-gg** [franck-vmd/Boeing-777-Flightgear#33]
lorsque l'on active le flight director (FD) cela désactive le plan de vol.

**Comment by franck-vmd** [comment]
Bonjour
Le bouton F/D est destiné à activer et désactiver le plan de vol. Tu peux l'activer directement par F/D, ou l'activer par cdu ----> F/D ----> cdu active , le mieux est activer  le plan de vol part F/D

**Comment by erwan-gg** [comment]
D’accord bien reçu 
Mais est-ce que se serait possible d’avoir un flight director de couleur rose comme sur l’image? 
![IMG_8670](https://github.com/user-attachments/assets/26ee5888-3352-4d07-936b-c65cbb8d8f44)

**Comment by franck-vmd** [comment]
ok pour un flight director de couleur rose
