### ISSUE TITLE
Similar Boeing 777

### ISSUE THREAD

**Issue by NG-Flightsim** [franck-vmd/Boeing-777-Flightgear#36]
Hey frank,
https://sourceforge.net/p/flightgear/fgaddon/HEAD/tree/trunk/Aircraft/777/
At this link, you'll find a 777 very similar to the one you've modelled, but the issue is that the LNAV of the autopilot doesn't work, so if you don't mind, could you help to fix it and upload it here on Github.

**Comment by franck-vmd** [comment]
Hi, I’m sorry but mine is taking a lot of time. Get in touch with them. 
Thank you
