### ISSUE TITLE
APU and Autopilot disengaged.

### ISSUE THREAD

**Issue by NG-Flightsim** [franck-vmd/Boeing-777-Flightgear#39]
The APU can't be switched off by clicking on it, I have to go to the Aircraft checklists to switch it off from there, could that be fixed, and also whenever I toggle instant flight replay, and it plays over the part where I disengaged the autopilot , the voice that repeats "Captain autopilot disengaged, careful check pitch trim" plays on loop and its annoying, could that also be removed.

**Comment by franck-vmd** [comment]
Hello for the apu click on the mouse wheel

**Comment by franck-vmd** [comment]
Hello, for the track uncheck box 3 and restart Flightgear
Tell me if everything is good for you 
![voie off](https://github.com/user-attachments/assets/19b9b558-2911-47ae-8ff3-738e37728b09)
