### ISSUE TITLE
Flightgear 2024.2

### ISSUE THREAD

**Issue by N929Q** [franck-vmd/Boeing-777-Flightgear#42]
For some reason it has difficulty loading in version 2024.2. I could only get it to load once, it took a long time, but cannot get it to load anymore. It stops when it gets to the load scenery on the splash screen.

**Comment by franck-vmd** [comment]
Hello, I can't check this version of flightgear, sorry, it works fine on 2020.03.19

**Comment by N929Q** [comment]
If you would like that version, 2020.4 / 2024.2, I have the latest as of 10/12/2024, let me know, I have it for windows.

**Comment by franck-vmd** [comment]
Hello and thank you but I am on Linux

**Comment by franck-vmd** [comment]
Hello, it should be good now, you can tell me if it's ok

**Comment by N929Q** [comment]
Thank you, yes it does load now. I appreciate it very much.

Bryce

**Comment by franck-vmd** [comment]
Hello and thank you for the feedback.
